[build-system]
requires = ["poetry_core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
dirty = true
metadata = true

[tool.poetry]
name = "lukebot"
version = "0.0.0"
authors = [
  "Exlot <author@example.com>" , "Charlie Wilson <charles.ep.wilson@gmail.com>",
]
description = "Discord bot for posting Luke updates"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Framework :: Pytest",
    "Natural Language :: English",
    "Topic :: Games/Entertainment",
]

[tool.poetry.dependencies]
requests = "~2.28.1"
python-dotenv="~0.20.0"
"discord.py"="~1.6.0"

[project.dev-dependencies]
test = [
  "pytest~=7.1.2",
  "dpytest~=0.5.3",
  "flake8~=4.0.1",
]

[tool.poetry.urls]
"Homepage" = "https://github.com/tolxe/LukeBot"
"repository" = "https://github.com/tolxe/LukeBot"
"Bug Tracker" = "https://github.com/tolxe/LukeBot/issues"

[tool.poetry.scripts]
start-lukebot = "luke_bot.main:main"




