name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted
    permissions:
      packages: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/tolxe/lukebot:latest
      - run: >
          docker run -d  
          -e "GG_TOKEN=${{ secrets.PROD_GG_TOKEN }}" 
          -e "DISCORD_TOKEN=${{ secrets.PROD_DISCORD_TOKEN }}"
          -e "DISCORD_CHANNEL_ID=${{ secrets.PROD_DISCORD_CHANNEL_ID }}"
          ghcr.io/tolxe/lukebot:latest
